language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
- npm install -g bower
install: npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm run update-webdriver
- bower install
- grunt test
- grunt build
after_success:
- cd $TRAVIS_BUILD_DIR/dist/
- find . -type f -exec curl -u $DEPLOY_USERNAME:$DEPLOY_PASSWORD --ftp-create-dirs
  -T {} $DEPLOY_HOST/$DEPLOY_REMOTEDIR/{} \;
env:
  global:
    secure: M4MGdUCkqriA+UjvtV/YHHACY6Qqv8d1gfCulsqati7ZCackNQuLf3v/X8VfMSG4TOFS6aZcAcvAO0Mkiv4FahgiGzO+bPJRKfevX3SGP+GUGNcQD9LuD6CufeKT6GNf5CU7rjOT0tC+pJ/UH8apWyfD18niXTj0/8mB7givyVs=
notifications:
  slack:
    secure: F1JID7ojAJXQ2X2I9KKtD5EEM5vKkIo1FNZuaZd315I6+M3GDComnfobRIHldOIMg2C1o41eZNJK/K8avJN0tBNJy01D/gSNZBo2nP8dfpVEMmZn4z3w0kLzQbJErXMYSV/jdMN0CyjzGf62KMVrfv8qItRQ6+zuFhye/2elRis=
